### ISSUE TITLE
hicodet version

### ISSUE THREAD

**Issue by SISTMrL** [kakaobrain/HOTR#1]
hello, what a wonderful work, could you provide the hicodet version, thanks!

**Comment by meliketoy** [comment]
Hi, we will update this version during this summer :) (We are working on some improvements for the released version of the code).
Thanks for your attention!

**Comment by SISTMrL** [comment]
@meliketoy ok, thanks, looking forward to your release, thanks!

**Comment by SISTMrL** [comment]
@meliketoy hi, could you please release the hicodet code for current version to me? the performance is not best is ok, thanks!

**Comment by dragen1860** [comment]
@meliketoy Yes, +1. Please just update a draft version for hicodet and demo code.

**Comment by meliketoy** [comment]
@SISTMrL @dragen1860 The HICO-DET version has been updated!
