### ISSUE TITLE
detr finetuned on the hicodet

### ISSUE THREAD

**Issue by SISTMrL** [kakaobrain/HOTR#11]
hello, could you please provide the detr pretrain model finetuned on hicodet, looking forward to your reply, thanks!

**Comment by bmsookim** [comment]
The link for the fine-tuned model has been uploaded :)

**Comment by SISTMrL** [comment]
@meliketoy hello, i'm sorry to disturb you. i want to obtain the detr model finutuned on hicodet: https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth,this link is detr trained on coco ,not the hotr model trained on finetuned detr, looking forward to your reply thanks!
