### ISSUE TITLE
output of hoi matcher 

### ISSUE THREAD

**Issue by SISTMrL** [kakaobrain/HOTR#2]
hello, i spend some time to read the code of hotr_matcher.py, but i couldn't understand it clearly. when i debug the code, the output of hotr_matcher.py is [(tensor([1]), tensor([0])), (tensor([4]), tensor([0]))] with bs=2, could you explain the meaning of this output? each element represents what? thanks very much, looking forward to your reply!

**Comment by meliketoy** [comment]
@SISTMrL The output of hotr_matcher.py is a pair of matching indices that maps the index of the N predictions of the interaction decoder with the index of the ground-truth labels.
The meaning of the given output [(tensor([1]), tensor([0])), (tensor([4]), tensor([0]))] is that
for the first batch, the prediction[1] is mapped with gt[0] and for the second batch, the prediction[4] is mapped with gt[0].

**Comment by SISTMrL** [comment]
@meliketoy thanks for explain. i have for another question. in your paper, you said you use h_pointer and o_pointer's embedding to calculate similarity with the instance representations(detr's output). how to find the match index between h_pointer ,o_pointer and instance representations.  i read the code of hotr_matcher.py, i think this two line code illustrate the match relationships, but i'm not sure, could you please explain it ?
![image](https://user-images.githubusercontent.com/47938053/123899434-c4ce2500-d999-11eb-8f53-be36f76b1398.png)

**Comment by meliketoy** [comment]
The tgt_hids and the tgt_oids contain the indices that best match the ground-truth labels.
The given two lines of code get the cost of the probability of the given classes (actually the cost will be 1-p, but is omitted since it is on the same scale,  refer to DETR for more details).

**Comment by SISTMrL** [comment]
@meliketoy ok , thanks,
