### ISSUE TITLE
demo code

### ISSUE THREAD

**Issue by dragen1860** [kakaobrain/HOTR#3]
Dear author:
  Thanks for sharing the training and validation code. A lot of researchers, just like me, want to quickly try your work and test it on custom images. Would you kindly share the demo code to inference on single image? Thank you very much.

**Comment by meliketoy** [comment]
@dragen1860 Will provide this very soon :) Thanks for your support!

**Comment by buaaswf** [comment]
Dear @meliketoy,
We attempt to draw the interaction results in the images, could you please tell us that whether the inst_target is the interaction actions?

**Comment by wolfworld6** [comment]
> Dear @meliketoy, We attempt to draw the interaction results in the images, could you please tell us that whether the inst_target is the interaction actions?

have you done this wonderful work?
