### ISSUE TITLE
the question of loss log

### ISSUE THREAD

**Issue by SISTMrL** [kakaobrain/HOTR#4]
hello, i read the code of loss calculation, you take loss_value and loss_dict_reduced_scaled to metric_logger as input. but your metric_logger class is difficult for me to understand. so i have three questions about the loss log. as is shown in figure
![image](https://user-images.githubusercontent.com/47938053/124644497-ead95500-dec4-11eb-85a8-9778a6501f53.png)

1. i saw each loss have two items such as: loss_act:1.3329(1.5253), how the meaning of 1.3329 and 1.5253
2. the loss_value is sum of loss_dict_reduced_scaled's values. but when i add the each loss respectively, as is shown in figure
![image](https://user-images.githubusercontent.com/47938053/124644877-51f70980-dec5-11eb-8803-c51774fdf571.png)
the  sum 21.6664 != 24.1092, but the other sum is correct, can you explain it?
3. when i saw the loss in the training process, which loss should i pay attention to? the loss in the parentheses or loss is outside parenthneses.

looking foward to your reply! thanks!

**Comment by dragen1860** [comment]
@SISTMrL I also working on this work and felt confused. Mayb we can keep in touch. add me via wechat: dragen1860

**Comment by meliketoy** [comment]
@SISTMrL @dragen1860 Actually this part of the code is not modified from the original DETR code. Please refer to this [issue](https://github.com/facebookresearch/detr/issues/333). Will help you further if this doesn't resolve your issues :)
