### ISSUE TITLE
the difference between inst_action, action, pairs_action?

### ISSUE THREAD

**Issue by dragen1860** [kakaobrain/HOTR#5]
Dear author:
   I understand the meaning of keys: roles, roles_bbox, roles_object_id in v-coco annotation files. But when i try to follow your code in vcoco dataset dataloader, I found these new variable, such as `inst_action` and `action`, `pair_actitons`, are really confusing for me. Could you kindly illustrate these variables? thank you.

**Comment by meliketoy** [comment]
@dragen1860 Hi, the inst_action are variables that are used in the 'AP_agent' evaluation mode (which is no longer used in HOI detection baselines). Therefore, you can simply ignore those variables.
