### ISSUE TITLE
parameter temperature

### ISSUE THREAD

**Issue by SISTMrL** [kakaobrain/HOTR#7]
hello, in your readme, you said the temperature is relative with number of decoder. but you don't tell us how to adjust the temperature according the number of decoders. looking forward to your reply, thanks!

**Comment by meliketoy** [comment]
There are no arithmetic relations between the temperature parameter and the final performance. We only just provide you vague results of the most representative parameters widely used in self-supervised learning :) You will have to explore it yourself.
