### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by SISTMrL** [kakaobrain/HOTR#8]
hello, when i'm going to reproduce the hicodet of hotr, i encounter the error follows:
FileNotFoundError: [Errno 2] No such file or directory: 'hico_20160224_det/list_action.txt'

could you provide the list_action.txt for me? thanks! i use the hicodet datasets i had download before, not your repo

looking forward to your reply, thanks!

**Comment by meliketoy** [comment]
We added instructions in README.md for this issue!

**Comment by SISTMrL** [comment]
@meliketoy thanks!!!!!
